export interface CollegeTeamInfo {
  name: string;
  abbr: string;
  espnId: number;
  mascot: string;
  conference: string;
  color: string;
  colorTo: string;
  /** 0-100 composite strength rating averaged across 2019-2025 seasons */
  historicalRating: number;
  /** Average points scored per game (2019-2025 avg) */
  avgPPG: number;
  /** Average points allowed per game (2019-2025 avg) */
  avgPAG: number;
  /** Home win percentage (2019-2025) */
  homeWinPct: number;
  /** Stadium name */
  stadium: string;
  /** Stadium capacity */
  capacity: number;
  /** Season-by-season win totals [2019, 2020, 2021, 2022, 2023, 2024] */
  seasonWins: number[];
  /** Season-by-season loss totals */
  seasonLosses: number[];
  /** AP Poll peaks (best ranking reached each year) */
  apPeaks: (number | null)[];
}

export const COLLEGE_TEAMS: Record<string, CollegeTeamInfo> = {
  ALA: {
    name: "Alabama Crimson Tide", abbr: "ALA", espnId: 333, mascot: "Crimson Tide", conference: "SEC",
    color: "#9E1B32", colorTo: "#828A8F", historicalRating: 94,
    avgPPG: 38.4, avgPAG: 14.2, homeWinPct: 0.93,
    stadium: "Bryant-Denny Stadium", capacity: 101821,
    seasonWins:   [13, 13, 13, 11, 12, 9],
    seasonLosses: [2,  0,  2,  2,  2,  4],
    apPeaks: [1, 1, 1, 6, 4, 12],
  },
  UGA: {
    name: "Georgia Bulldogs", abbr: "UGA", espnId: 61, mascot: "Bulldogs", conference: "SEC",
    color: "#BA0C2F", colorTo: "#000000", historicalRating: 95,
    avgPPG: 36.1, avgPAG: 11.8, homeWinPct: 0.94,
    stadium: "Sanford Stadium", capacity: 92746,
    seasonWins:   [12, 8,  11, 15, 13, 11],
    seasonLosses: [2,  2,  2,  0,  1,  3],
    apPeaks: [5, 7, 3, 1, 1, 6],
  },
  OSU: {
    name: "Ohio State Buckeyes", abbr: "OSU", espnId: 194, mascot: "Buckeyes", conference: "Big Ten",
    color: "#BB0000", colorTo: "#666666", historicalRating: 91,
    avgPPG: 40.2, avgPAG: 15.6, homeWinPct: 0.91,
    stadium: "Ohio Stadium (The Shoe)", capacity: 102780,
    seasonWins:   [13, 8,  11, 13, 12, 10],
    seasonLosses: [1,  1,  2,  1,  2,  2],
    apPeaks: [3, 3, 4, 3, 2, 1],
  },
  MICH: {
    name: "Michigan Wolverines", abbr: "MICH", espnId: 130, mascot: "Wolverines", conference: "Big Ten",
    color: "#00274C", colorTo: "#FFCB05", historicalRating: 86,
    avgPPG: 33.7, avgPAG: 14.1, homeWinPct: 0.88,
    stadium: "Michigan Stadium (The Big House)", capacity: 107601,
    seasonWins:   [9,  2,  12, 13, 15, 8],
    seasonLosses: [4,  4,  2,  1,  0,  5],
    apPeaks: [14, null, 6, 3, 1, 9],
  },
  CLEM: {
    name: "Clemson Tigers", abbr: "CLEM", espnId: 228, mascot: "Tigers", conference: "ACC",
    color: "#F56600", colorTo: "#522D80", historicalRating: 84,
    avgPPG: 33.1, avgPAG: 17.4, homeWinPct: 0.89,
    stadium: "Memorial Stadium (Death Valley)", capacity: 81500,
    seasonWins:   [10, 10, 10, 11, 9,  10],
    seasonLosses: [4,  2,  3,  3,  4,  4],
    apPeaks: [3, 3, 4, 5, 12, 10],
  },
  LSU: {
    name: "LSU Tigers", abbr: "LSU", espnId: 99, mascot: "Tigers", conference: "SEC",
    color: "#461D7C", colorTo: "#FDD023", historicalRating: 81,
    avgPPG: 33.8, avgPAG: 20.1, homeWinPct: 0.85,
    stadium: "Tiger Stadium (Death Valley)", capacity: 102321,
    seasonWins:   [15, 5,  6,  10, 10, 9],
    seasonLosses: [0,  5,  6,  4,  3,  4],
    apPeaks: [1, null, null, 7, 5, 8],
  },
  OKLA: {
    name: "Oklahoma Sooners", abbr: "OKLA", espnId: 201, mascot: "Sooners", conference: "SEC",
    color: "#841617", colorTo: "#FFF",historicalRating: 80,
    avgPPG: 36.4, avgPAG: 22.3, homeWinPct: 0.87,
    stadium: "Gaylord Family Oklahoma Memorial Stadium", capacity: 80126,
    seasonWins:   [12, 9,  11, 6,  10, 6],
    seasonLosses: [2,  2,  2,  7,  3,  7],
    apPeaks: [4, 5, 3, null, 11, null],
  },
  ND: {
    name: "Notre Dame Fighting Irish", abbr: "ND", espnId: 87, mascot: "Fighting Irish", conference: "Independent",
    color: "#0C2340", colorTo: "#C99700", historicalRating: 82,
    avgPPG: 30.2, avgPAG: 17.1, homeWinPct: 0.84,
    stadium: "Notre Dame Stadium", capacity: 77622,
    seasonWins:   [10, 10, 11, 9,  12, 14],
    seasonLosses: [2,  2,  2,  4,  2,  2],
    apPeaks: [4, 4, 5, 9, 6, 1],
  },
  PSU: {
    name: "Penn State Nittany Lions", abbr: "PSU", espnId: 213, mascot: "Nittany Lions", conference: "Big Ten",
    color: "#041E42", colorTo: "#FFFFFF", historicalRating: 80,
    avgPPG: 30.6, avgPAG: 16.8, homeWinPct: 0.86,
    stadium: "Beaver Stadium", capacity: 106572,
    seasonWins:   [11, 4,  11, 11, 10, 13],
    seasonLosses: [3,  5,  2,  2,  3,  3],
    apPeaks: [7, null, 4, 7, 10, 4],
  },
  TEX: {
    name: "Texas Longhorns", abbr: "TEX", espnId: 251, mascot: "Longhorns", conference: "SEC",
    color: "#BF5700", colorTo: "#FFFFFF", historicalRating: 79,
    avgPPG: 33.2, avgPAG: 19.4, homeWinPct: 0.83,
    stadium: "Darrell K Royal–Texas Memorial Stadium", capacity: 100119,
    seasonWins:   [8,  7,  5,  8,  12, 13],
    seasonLosses: [5,  3,  7,  5,  2,  3],
    apPeaks: [null, null, null, null, 3, 5],
  },
  USC: {
    name: "USC Trojans", abbr: "USC", espnId: 30, mascot: "Trojans", conference: "Big Ten",
    color: "#990000", colorTo: "#FFC72C", historicalRating: 75,
    avgPPG: 34.7, avgPAG: 22.1, homeWinPct: 0.80,
    stadium: "Los Angeles Memorial Coliseum", capacity: 77500,
    seasonWins:   [5,  5,  11, 11, 8,  7],
    seasonLosses: [7,  1,  3,  3,  5,  6],
    apPeaks: [null, null, 7, 5, null, null],
  },
  ORE: {
    name: "Oregon Ducks", abbr: "ORE", espnId: 2483, mascot: "Ducks", conference: "Big Ten",
    color: "#154733", colorTo: "#FEE123", historicalRating: 78,
    avgPPG: 36.1, avgPAG: 20.4, homeWinPct: 0.84,
    stadium: "Autzen Stadium", capacity: 54000,
    seasonWins:   [4,  4,  10, 10, 12, 13],
    seasonLosses: [3,  3,  4,  3,  2,  1],
    apPeaks: [null, null, 4, 6, 3, 1],
  },
  FSU: {
    name: "Florida State Seminoles", abbr: "FSU", espnId: 52, mascot: "Seminoles", conference: "ACC",
    color: "#782F40", colorTo: "#CEB888", historicalRating: 74,
    avgPPG: 30.1, avgPAG: 20.7, homeWinPct: 0.79,
    stadium: "Doak Campbell Stadium", capacity: 79560,
    seasonWins:   [6,  8,  5,  10, 13, 2],
    seasonLosses: [7,  3,  7,  3,  0,  10],
    apPeaks: [null, null, null, 6, 1, null],
  },
  TAMU: {
    name: "Texas A&M Aggies", abbr: "TAMU", espnId: 245, mascot: "Aggies", conference: "SEC",
    color: "#500000", colorTo: "#FFFFFF", historicalRating: 73,
    avgPPG: 29.4, avgPAG: 18.6, homeWinPct: 0.81,
    stadium: "Kyle Field", capacity: 102733,
    seasonWins:   [9,  9,  8,  5,  7,  8],
    seasonLosses: [4,  1,  4,  7,  5,  4],
    apPeaks: [9, 4, 13, null, null, null],
  },
  FLA: {
    name: "Florida Gators", abbr: "FLA", espnId: 57, mascot: "Gators", conference: "SEC",
    color: "#0021A5", colorTo: "#FA4616", historicalRating: 70,
    avgPPG: 27.8, avgPAG: 20.9, homeWinPct: 0.77,
    stadium: "Ben Hill Griffin Stadium (The Swamp)", capacity: 88548,
    seasonWins:   [8,  8,  6,  6,  5,  8],
    seasonLosses: [4,  4,  7,  7,  7,  5],
    apPeaks: [7, 6, null, null, null, null],
  },
  TENN: {
    name: "Tennessee Volunteers", abbr: "TENN", espnId: 2633, mascot: "Volunteers", conference: "SEC",
    color: "#FF8200", colorTo: "#FFFFFF", historicalRating: 72,
    avgPPG: 31.7, avgPAG: 19.4, homeWinPct: 0.80,
    stadium: "Neyland Stadium", capacity: 101915,
    seasonWins:   [3,  3,  8,  11, 9,  10],
    seasonLosses: [7,  7,  4,  2,  4,  4],
    apPeaks: [null, null, null, 6, 5, 6],
  },
  AUB: {
    name: "Auburn Tigers", abbr: "AUB", espnId: 2, mascot: "Tigers", conference: "SEC",
    color: "#0C2340", colorTo: "#E87722", historicalRating: 68,
    avgPPG: 28.3, avgPAG: 22.1, homeWinPct: 0.76,
    stadium: "Jordan-Hare Stadium", capacity: 87451,
    seasonWins:   [7,  6,  6,  5,  6,  5],
    seasonLosses: [5,  5,  6,  7,  7,  7],
    apPeaks: [null, null, null, null, null, null],
  },
  MISS: {
    name: "Ole Miss Rebels", abbr: "MISS", espnId: 145, mascot: "Rebels", conference: "SEC",
    color: "#CE1126", colorTo: "#14213D", historicalRating: 71,
    avgPPG: 35.2, avgPAG: 24.6, homeWinPct: 0.78,
    stadium: "Vaught-Hemingway Stadium", capacity: 64038,
    seasonWins:   [4,  5,  10, 8,  11, 9],
    seasonLosses: [8,  5,  3,  5,  2,  3],
    apPeaks: [null, null, 9, null, 7, 8],
  },
  ARK: {
    name: "Arkansas Razorbacks", abbr: "ARK", espnId: 8, mascot: "Razorbacks", conference: "SEC",
    color: "#9D2235", colorTo: "#FFFFFF", historicalRating: 65,
    avgPPG: 27.6, avgPAG: 24.4, homeWinPct: 0.72,
    stadium: "Donald W. Reynolds Razorback Stadium", capacity: 76416,
    seasonWins:   [4,  3,  9,  7,  4,  6],
    seasonLosses: [8,  7,  4,  6,  8,  6],
    apPeaks: [null, null, 8, null, null, null],
  },
  MSU: {
    name: "Michigan State Spartans", abbr: "MSU", espnId: 127, mascot: "Spartans", conference: "Big Ten",
    color: "#18453B", colorTo: "#FFFFFF", historicalRating: 66,
    avgPPG: 27.1, avgPAG: 20.3, homeWinPct: 0.73,
    stadium: "Spartan Stadium", capacity: 75005,
    seasonWins:   [7,  2,  11, 5,  4,  5],
    seasonLosses: [6,  5,  2,  7,  8,  7],
    apPeaks: [null, null, 3, null, null, null],
  },
  IOWA: {
    name: "Iowa Hawkeyes", abbr: "IOWA", espnId: 2294, mascot: "Hawkeyes", conference: "Big Ten",
    color: "#000000", colorTo: "#FFCD00", historicalRating: 68,
    avgPPG: 23.1, avgPAG: 17.8, homeWinPct: 0.75,
    stadium: "Kinnick Stadium", capacity: 69250,
    seasonWins:   [10, 6,  10, 8,  6,  8],
    seasonLosses: [4,  2,  4,  5,  7,  5],
    apPeaks: [8, null, 2, null, null, null],
  },
  WISC: {
    name: "Wisconsin Badgers", abbr: "WISC", espnId: 275, mascot: "Badgers", conference: "Big Ten",
    color: "#C5050C", colorTo: "#FFFFFF", historicalRating: 67,
    avgPPG: 27.8, avgPAG: 18.4, homeWinPct: 0.79,
    stadium: "Camp Randall Stadium", capacity: 80321,
    seasonWins:   [10, 4,  9,  7,  7,  6],
    seasonLosses: [4,  3,  4,  6,  6,  7],
    apPeaks: [13, null, 8, null, null, null],
  },
  MINN: {
    name: "Minnesota Golden Gophers", abbr: "MINN", espnId: 135, mascot: "Golden Gophers", conference: "Big Ten",
    color: "#7A0019", colorTo: "#FFCC33", historicalRating: 62,
    avgPPG: 25.4, avgPAG: 21.3, homeWinPct: 0.70,
    stadium: "Huntington Bank Stadium", capacity: 50805,
    seasonWins:   [11, 3,  9,  9,  4,  8],
    seasonLosses: [2,  4,  4,  4,  8,  4],
    apPeaks: [10, null, null, null, null, null],
  },
  ILL: {
    name: "Illinois Fighting Illini", abbr: "ILL", espnId: 356, mascot: "Fighting Illini", conference: "Big Ten",
    color: "#13294B", colorTo: "#E84A27", historicalRating: 55,
    avgPPG: 21.8, avgPAG: 23.6, homeWinPct: 0.62,
    stadium: "Memorial Stadium", capacity: 60670,
    seasonWins:   [6,  2,  5,  8,  5,  9],
    seasonLosses: [7,  6,  7,  5,  7,  4],
    apPeaks: [null, null, null, 12, null, null],
  },
  UCLA: {
    name: "UCLA Bruins", abbr: "UCLA", espnId: 26, mascot: "Bruins", conference: "Big Ten",
    color: "#2D68C4", colorTo: "#F2A900", historicalRating: 63,
    avgPPG: 29.6, avgPAG: 23.1, homeWinPct: 0.72,
    stadium: "Rose Bowl", capacity: 90888,
    seasonWins:   [4,  3,  8,  9,  8,  3],
    seasonLosses: [8,  4,  4,  4,  5,  9],
    apPeaks: [null, null, null, 12, null, null],
  },
  WASH: {
    name: "Washington Huskies", abbr: "WASH", espnId: 264, mascot: "Huskies", conference: "Big Ten",
    color: "#4B2E83", colorTo: "#B7A57A", historicalRating: 74,
    avgPPG: 34.1, avgPAG: 19.3, homeWinPct: 0.82,
    stadium: "Husky Stadium", capacity: 70138,
    seasonWins:   [8,  3,  4,  11, 14, 6],
    seasonLosses: [4,  1,  8,  2,  1,  7],
    apPeaks: [null, null, null, 7, 2, null],
  },
  UTAH: {
    name: "Utah Utes", abbr: "UTAH", espnId: 254, mascot: "Utes", conference: "Big 12",
    color: "#CC0000", colorTo: "#FFFFFF", historicalRating: 71,
    avgPPG: 30.7, avgPAG: 19.8, homeWinPct: 0.80,
    stadium: "Rice-Eccles Stadium", capacity: 51444,
    seasonWins:   [11, 3,  11, 10, 8,  5],
    seasonLosses: [3,  3,  3,  4,  5,  7],
    apPeaks: [7, null, 8, 5, null, null],
  },
  OKST: {
    name: "Oklahoma State Cowboys", abbr: "OKST", espnId: 197, mascot: "Cowboys", conference: "Big 12",
    color: "#FF6600", colorTo: "#000000", historicalRating: 70,
    avgPPG: 31.8, avgPAG: 22.4, homeWinPct: 0.79,
    stadium: "Boone Pickens Stadium", capacity: 55509,
    seasonWins:   [8,  8,  12, 7,  7,  8],
    seasonLosses: [4,  3,  2,  6,  6,  5],
    apPeaks: [null, null, 4, null, null, null],
  },
  KSU: {
    name: "Kansas State Wildcats", abbr: "KSU", espnId: 2306, mascot: "Wildcats", conference: "Big 12",
    color: "#512888", colorTo: "#FFFFFF", historicalRating: 67,
    avgPPG: 28.7, avgPAG: 21.3, homeWinPct: 0.77,
    stadium: "Bill Snyder Family Football Stadium", capacity: 50000,
    seasonWins:   [8,  4,  8,  10, 9,  9],
    seasonLosses: [4,  6,  5,  4,  4,  4],
    apPeaks: [null, null, null, 7, null, null],
  },
  BAY: {
    name: "Baylor Bears", abbr: "BAY", espnId: 239, mascot: "Bears", conference: "Big 12",
    color: "#003015", colorTo: "#FBBF15", historicalRating: 64,
    avgPPG: 30.1, avgPAG: 22.8, homeWinPct: 0.75,
    stadium: "McLane Stadium", capacity: 45140,
    seasonWins:   [11, 2,  12, 7,  8,  7],
    seasonLosses: [3,  7,  2,  6,  5,  6],
    apPeaks: [7, null, 5, null, null, null],
  },
  TCU: {
    name: "TCU Horned Frogs", abbr: "TCU", espnId: 2628, mascot: "Horned Frogs", conference: "Big 12",
    color: "#4D1979", colorTo: "#A3A9AC", historicalRating: 66,
    avgPPG: 29.4, avgPAG: 21.6, homeWinPct: 0.76,
    stadium: "Amon G. Carter Stadium", capacity: 47000,
    seasonWins:   [5,  6,  5,  13, 5,  7],
    seasonLosses: [7,  6,  7,  2,  8,  5],
    apPeaks: [null, null, null, 2, null, null],
  },
  TTU: {
    name: "Texas Tech Red Raiders", abbr: "TTU", espnId: 2641, mascot: "Red Raiders", conference: "Big 12",
    color: "#CC0000", colorTo: "#000000", historicalRating: 60,
    avgPPG: 30.4, avgPAG: 27.1, homeWinPct: 0.70,
    stadium: "Jones AT&T Stadium", capacity: 60454,
    seasonWins:   [4,  4,  7,  8,  7,  8],
    seasonLosses: [8,  4,  6,  5,  6,  5],
    apPeaks: [null, null, null, null, null, null],
  },
  BYU: {
    name: "BYU Cougars", abbr: "BYU", espnId: 252, mascot: "Cougars", conference: "Big 12",
    color: "#002E5D", colorTo: "#FFFFFF", historicalRating: 64,
    avgPPG: 29.8, avgPAG: 21.7, homeWinPct: 0.77,
    stadium: "LaVell Edwards Stadium", capacity: 63470,
    seasonWins:   [5,  11, 10, 9,  5,  10],
    seasonLosses: [7,  1,  3,  4,  7,  3],
    apPeaks: [null, 8, null, null, null, null],
  },
  ISU: {
    name: "Iowa State Cyclones", abbr: "ISU", espnId: 66, mascot: "Cyclones", conference: "Big 12",
    color: "#C8102E", colorTo: "#F1BE48", historicalRating: 60,
    avgPPG: 27.3, avgPAG: 22.8, homeWinPct: 0.72,
    stadium: "Jack Trice Stadium", capacity: 61500,
    seasonWins:   [7,  9,  7,  4,  7,  7],
    seasonLosses: [6,  3,  6,  8,  5,  6],
    apPeaks: [null, 10, null, null, null, null],
  },
  CIN: {
    name: "Cincinnati Bearcats", abbr: "CIN", espnId: 2132, mascot: "Bearcats", conference: "Big 12",
    color: "#E00122", colorTo: "#000000", historicalRating: 66,
    avgPPG: 32.4, avgPAG: 18.4, homeWinPct: 0.82,
    stadium: "Nippert Stadium", capacity: 40000,
    seasonWins:   [11, 9,  13, 9,  6,  9],
    seasonLosses: [3,  1,  1,  4,  7,  4],
    apPeaks: [7, null, 4, null, null, null],
  },
  UCF: {
    name: "UCF Knights", abbr: "UCF", espnId: 2116, mascot: "Knights", conference: "Big 12",
    color: "#BA9B37", colorTo: "#000000", historicalRating: 58,
    avgPPG: 31.7, avgPAG: 24.6, homeWinPct: 0.73,
    stadium: "FBC Mortgage Stadium", capacity: 44206,
    seasonWins:   [10, 6,  9,  9,  6,  9],
    seasonLosses: [3,  4,  4,  5,  7,  4],
    apPeaks: [null, null, null, null, null, null],
  },
  NCST: {
    name: "NC State Wolfpack", abbr: "NCST", espnId: 152, mascot: "Wolfpack", conference: "ACC",
    color: "#CC0000", colorTo: "#FFFFFF", historicalRating: 62,
    avgPPG: 27.8, avgPAG: 21.4, homeWinPct: 0.74,
    stadium: "Carter-Finley Stadium", capacity: 57583,
    seasonWins:   [9,  8,  9,  9,  9,  5],
    seasonLosses: [3,  4,  3,  5,  4,  7],
    apPeaks: [null, null, null, null, null, null],
  },
  UNC: {
    name: "North Carolina Tar Heels", abbr: "UNC", espnId: 153, mascot: "Tar Heels", conference: "ACC",
    color: "#56A0D3", colorTo: "#FFFFFF", historicalRating: 61,
    avgPPG: 29.4, avgPAG: 23.8, homeWinPct: 0.71,
    stadium: "Kenan Memorial Stadium", capacity: 63500,
    seasonWins:   [3,  8,  11, 9,  8,  4],
    seasonLosses: [9,  4,  3,  4,  5,  8],
    apPeaks: [null, null, 10, null, null, null],
  },
  PITT: {
    name: "Pittsburgh Panthers", abbr: "PITT", espnId: 221, mascot: "Panthers", conference: "ACC",
    color: "#003594", colorTo: "#FFB81C", historicalRating: 63,
    avgPPG: 27.1, avgPAG: 22.3, homeWinPct: 0.73,
    stadium: "Acrisure Stadium", capacity: 68400,
    seasonWins:   [8,  6,  11, 8,  7,  9],
    seasonLosses: [5,  5,  3,  6,  6,  4],
    apPeaks: [null, null, 13, null, null, null],
  },
  VT: {
    name: "Virginia Tech Hokies", abbr: "VT", espnId: 259, mascot: "Hokies", conference: "ACC",
    color: "#630031", colorTo: "#CF4420", historicalRating: 60,
    avgPPG: 24.4, avgPAG: 22.1, homeWinPct: 0.70,
    stadium: "Lane Stadium", capacity: 66233,
    seasonWins:   [8,  5,  6,  3,  7,  6],
    seasonLosses: [4,  6,  6,  9,  5,  6],
    apPeaks: [null, null, null, null, null, null],
  },
  GT: {
    name: "Georgia Tech Yellow Jackets", abbr: "GT", espnId: 59, mascot: "Yellow Jackets", conference: "ACC",
    color: "#B3A369", colorTo: "#003057", historicalRating: 55,
    avgPPG: 21.8, avgPAG: 24.6, homeWinPct: 0.65,
    stadium: "Bobby Dodd Stadium", capacity: 55000,
    seasonWins:   [3,  3,  3,  8,  7,  11],
    seasonLosses: [9,  7,  9,  5,  6,  3],
    apPeaks: [null, null, null, null, null, null],
  },
  LOU: {
    name: "Louisville Cardinals", abbr: "LOU", espnId: 97, mascot: "Cardinals", conference: "ACC",
    color: "#AD0000", colorTo: "#000000", historicalRating: 60,
    avgPPG: 28.7, avgPAG: 24.8, homeWinPct: 0.72,
    stadium: "L&N Federal Credit Union Stadium", capacity: 61000,
    seasonWins:   [8,  4,  6,  8,  10, 9],
    seasonLosses: [5,  7,  6,  4,  3,  4],
    apPeaks: [null, null, null, null, 11, null],
  },
  MIA: {
    name: "Miami Hurricanes", abbr: "MIA", espnId: 2390, mascot: "Hurricanes", conference: "ACC",
    color: "#F47321", colorTo: "#005030", historicalRating: 65,
    avgPPG: 29.6, avgPAG: 22.4, homeWinPct: 0.76,
    stadium: "Hard Rock Stadium", capacity: 65326,
    seasonWins:   [6,  8,  7,  11, 7,  10],
    seasonLosses: [7,  3,  5,  3,  6,  3],
    apPeaks: [null, null, null, 13, null, 5],
  },
  NEB: {
    name: "Nebraska Cornhuskers", abbr: "NEB", espnId: 158, mascot: "Cornhuskers", conference: "Big Ten",
    color: "#E41C38", colorTo: "#FFFFFF", historicalRating: 57,
    avgPPG: 22.8, avgPAG: 24.6, homeWinPct: 0.67,
    stadium: "Memorial Stadium", capacity: 86047,
    seasonWins:   [5,  3,  3,  4,  5,  7],
    seasonLosses: [7,  5,  9,  8,  7,  6],
    apPeaks: [null, null, null, null, null, null],
  },
  BSU: {
    name: "Boise State Broncos", abbr: "BSU", espnId: 68, mascot: "Broncos", conference: "Mountain West",
    color: "#0033A0", colorTo: "#D64309", historicalRating: 67,
    avgPPG: 30.6, avgPAG: 17.8, homeWinPct: 0.84,
    stadium: "Albertsons Stadium (The Blue Turf)", capacity: 36387,
    seasonWins:   [12, 5,  7,  10, 10, 7],
    seasonLosses: [2,  2,  5,  4,  3,  6],
    apPeaks: [13, null, null, null, 16, null],
  },
  APP: {
    name: "Appalachian State Mountaineers", abbr: "APP", espnId: 2026, mascot: "Mountaineers", conference: "Sun Belt",
    color: "#FFD200", colorTo: "#000000", historicalRating: 63,
    avgPPG: 31.2, avgPAG: 19.6, homeWinPct: 0.83,
    stadium: "Kidd Brewer Stadium", capacity: 30000,
    seasonWins:   [13, 9,  10, 11, 6,  8],
    seasonLosses: [1,  3,  3,  2,  6,  4],
    apPeaks: [19, null, null, null, null, null],
  },
  TUL: {
    name: "Tulane Green Wave", abbr: "TUL", espnId: 2655, mascot: "Green Wave", conference: "AAC",
    color: "#006747", colorTo: "#418FDE", historicalRating: 58,
    avgPPG: 29.8, avgPAG: 22.1, homeWinPct: 0.76,
    stadium: "Yulman Stadium", capacity: 30000,
    seasonWins:   [7,  6,  2,  12, 11, 9],
    seasonLosses: [6,  6,  10, 2,  3,  4],
    apPeaks: [null, null, null, 18, null, null],
  },
  SDSU: {
    name: "San Diego State Aztecs", abbr: "SDSU", espnId: 21, mascot: "Aztecs", conference: "Mountain West",
    color: "#A6192E", colorTo: "#000000", historicalRating: 60,
    avgPPG: 24.1, avgPAG: 18.6, homeWinPct: 0.79,
    stadium: "Snapdragon Stadium", capacity: 35000,
    seasonWins:   [11, 4,  12, 7,  9,  7],
    seasonLosses: [3,  4,  2,  6,  4,  5],
    apPeaks: [null, null, null, null, null, null],
  },
  ARMY: {
    name: "Army Black Knights", abbr: "ARMY", espnId: 349, mascot: "Black Knights", conference: "Independent",
    color: "#000000", colorTo: "#FFD700", historicalRating: 58,
    avgPPG: 28.4, avgPAG: 17.6, homeWinPct: 0.78,
    stadium: "Michie Stadium", capacity: 38000,
    seasonWins:   [5,  9,  9,  8,  5,  12],
    seasonLosses: [8,  3,  3,  4,  7,  2],
    apPeaks: [null, null, null, null, null, null],
  },
};

export const CONFERENCE_STRENGTH: Record<string, number> = {
  "SEC":            1.00,
  "Big Ten":        0.95,
  "Big 12":        0.85,
  "ACC":            0.80,
  "Pac-12":         0.78,
  "Mountain West":  0.65,
  "AAC":            0.62,
  "Sun Belt":       0.58,
  "MAC":            0.52,
  "CUSA":           0.50,
  "Independent":    0.72,
};

export function getCollegeTeam(abbr: string): CollegeTeamInfo {
  return (
    COLLEGE_TEAMS[abbr?.toUpperCase()] || {
      name: abbr || "Unknown",
      abbr: abbr || "UNK",
      espnId: 0,
      mascot: "",
      conference: "Independent",
      color: "#1a1a2e",
      colorTo: "#16213e",
      historicalRating: 50,
      avgPPG: 24.0,
      avgPAG: 24.0,
      homeWinPct: 0.55,
      stadium: "Unknown Stadium",
      capacity: 30000,
      seasonWins:   [6, 6, 6, 6, 6, 6],
      seasonLosses: [6, 6, 6, 6, 6, 6],
      apPeaks: [null, null, null, null, null, null],
    }
  );
}

export const COLLEGE_TEAM_LIST = Object.values(COLLEGE_TEAMS);

/** ESPN logo URL for college teams */
export function collegeLogoUrl(espnId: number): string {
  return `https://a.espncdn.com/i/teamlogos/ncaa/500/${espnId}.png`;
}

export function espnAbbrToCollegeAbbr(espnAbbr: string): string {
  const map: Record<string, string> = {
    "ALA": "ALA", "GA": "UGA", "OSU": "OSU", "MICH": "MICH",
    "CLEM": "CLEM", "LSU": "LSU", "OKLA": "OKLA", "ND": "ND",
    "PSU": "PSU", "TEX": "TEX", "USC": "USC", "ORE": "ORE",
    "FSU": "FSU", "TAMU": "TAMU", "FLA": "FLA", "TENN": "TENN",
    "AUB": "AUB", "MISS": "MISS", "ARK": "ARK", "MIST": "MSU",
    "IOWA": "IOWA", "WIS": "WISC", "MINN": "MINN", "ILL": "ILL",
    "UCLA": "UCLA", "WASH": "WASH", "UTAH": "UTAH", "OKST": "OKST",
    "KSU": "KSU", "BAY": "BAY", "TCU": "TCU", "TTU": "TTU",
    "BYU": "BYU", "ISU": "ISU", "CIN": "CIN", "UCF": "UCF",
    "NCST": "NCST", "UNC": "UNC", "PITT": "PITT", "VT": "VT",
    "GT": "GT", "LOU": "LOU", "MIA": "MIA", "NEB": "NEB",
    "BSU": "BSU", "APP": "APP", "TUL": "TUL", "SDSU": "SDSU",
    "ARMY": "ARMY",
  };
  return map[espnAbbr.toUpperCase()] || espnAbbr.toUpperCase();
}
