export interface TeamProfile {
  coach: string;
  qb: string;
  offenseStyle: string;
  defenseStyle: string;
  strength: string;
  weakness: string;
  keyPlayer1: { name: string; pos: string; note: string };
  keyPlayer2: { name: string; pos: string; note: string };
  outlook: string[];
}

export const NFL_TEAM_PROFILES: Record<string, TeamProfile> = {
  KC: {
    coach: "Andy Reid", qb: "Patrick Mahomes",
    offenseStyle: "dynamic, play-action heavy passing offense with elite pre-snap motion",
    defenseStyle: "multiple-front defense built around speed and disguise",
    strength: "Mahomes' ability to extend plays and create touchdowns outside of structure",
    weakness: "defensive depth at cornerback when starters are unavailable",
    keyPlayer1: { name: "Patrick Mahomes", pos: "QB", note: "The reigning standard-bearer at the position. Mahomes' combination of arm talent, mobility, and football IQ makes him nearly impossible to game-plan against consistently. Look for him to exploit single coverage and generate explosive plays in the second half." },
    keyPlayer2: { name: "Travis Kelce", pos: "TE", note: "Kelce remains the most reliable tight end in football in critical moments. His route running in the middle of the field and red-zone presence gives Mahomes a safety valve that defenses cannot fully eliminate." },
    outlook: ["Kansas City's offensive system under Andy Reid is the most refined in the NFL. The Chiefs consistently manufacture clean throws for Mahomes through creative motion, shifts, and play-action design.", "The Chiefs' defense is built for adaptability. Their ability to rotate coverages and generate pressure with four rushers keeps opposing offenses off-rhythm throughout games.", "Expect Kansas City to control possession time and protect early leads. Reid's teams rarely beat themselves — turnovers are low, penalties are managed, and situational football is a consistent strength."],
  },
  BAL: {
    coach: "John Harbaugh", qb: "Lamar Jackson",
    offenseStyle: "RPO-heavy run-pass option attack built around Jackson's dual-threat ability",
    defenseStyle: "aggressive, press-coverage defense with elite safety play",
    strength: "Jackson's rushing threat that forces defenses into impossible assignment conflicts",
    weakness: "consistency in the red zone when the run game is bottled up",
    keyPlayer1: { name: "Lamar Jackson", pos: "QB", note: "A two-time MVP whose rushing ability makes every Ravens drive a potential explosive play. Jackson's combination of arm talent and running ability forces defenses to account for him on every snap, opening the field for his receivers." },
    keyPlayer2: { name: "Zay Flowers", pos: "WR", note: "Flowers' speed and explosiveness after the catch complement Jackson's style perfectly. He creates mismatches in space and has become one of the AFC's most dangerous slot receivers when healthy." },
    outlook: ["Baltimore's offense begins and ends with Lamar Jackson's legs. When the Ravens can establish the run and control the line of scrimmage, their offense is nearly impossible to stop.", "John Harbaugh's defense is built on physicality. Baltimore takes away the opponent's primary option and dares them to beat them with their secondary or tertiary reads.", "The Ravens are at their best early — they impose their will physically and establish momentum in the first quarter. If they build a lead, their defense finishes the job."],
  },
  BUF: {
    coach: "Sean McDermott", qb: "Josh Allen",
    offenseStyle: "explosive, multi-faceted attack leveraging Allen's arm and legs equally",
    defenseStyle: "zone-heavy coverage scheme that maximizes their cornerback talent",
    strength: "Allen's physical dominance and ability to convert third downs with his legs",
    weakness: "late-game decision-making in high-pressure playoff situations",
    keyPlayer1: { name: "Josh Allen", pos: "QB", note: "Allen is the most physically gifted quarterback in football. His combination of arm strength and rushing ability gives Buffalo a weekly chance to beat any team in the league." },
    keyPlayer2: { name: "Stefon Diggs", pos: "WR", note: "Diggs' route precision and contested-catch ability make him Allen's most reliable target in critical moments. He wins on all three levels of the field and understands how to manipulate cornerback leverage." },
    outlook: ["Buffalo's offense is built around Josh Allen's ability to extend plays and create opportunities outside of structure. When the Bills get Allen moving, the entire defense has to account for both his passing and rushing threat.", "Sean McDermott's defensive scheme is built on discipline and assignment football. The Bills rarely give up easy touchdowns and force opposing offenses to be precise on every snap.", "Highmark Stadium is one of the most hostile environments for visiting teams in the NFL. The Bills' crowd advantage is genuine and has impacted many games in contested situations."],
  },
  PHI: {
    coach: "Nick Sirianni", qb: "Jalen Hurts",
    offenseStyle: "run-dominant, play-action system built around Hurts' mobility and a dominant offensive line",
    defenseStyle: "aggressive, blitz-heavy defense anchored by one of the best defensive fronts in football",
    strength: "offensive line depth and run game that controls possession and field position",
    weakness: "passing game consistency when facing elite cornerback matchups",
    keyPlayer1: { name: "Jalen Hurts", pos: "QB", note: "Hurts has developed into one of the NFC's most efficient quarterbacks. His rushing ability keeps defenses honest and creates the play-action opportunities that make the Eagles' vertical passing game effective." },
    keyPlayer2: { name: "A.J. Brown", pos: "WR", note: "Brown's combination of size and speed makes him one of the hardest receivers to match up against in the league. He's at his best in contested situations and consistently wins in the red zone." },
    outlook: ["Philadelphia's offensive line is the foundation of everything they do. When the Eagles can run the football and control the line of scrimmage, their offense becomes nearly impossible to defend for a full sixty minutes.", "Nick Sirianni's defense generates pressure with four rushers consistently, which allows the secondary to play aggressive man coverage.", "The Eagles are a second-half team. Their physicality and depth wear opponents down as games progress."],
  },
  SF: {
    coach: "Kyle Shanahan", qb: "Brock Purdy",
    offenseStyle: "wide-zone running scheme with layered play-action and creative receiver usage",
    defenseStyle: "versatile, multiple-front defense that shifts personnel based on the opponent",
    strength: "Shanahan's scheme creativity that generates clean looks for Purdy on every down",
    weakness: "injury history at key positions that has derailed multiple postseason runs",
    keyPlayer1: { name: "Brock Purdy", pos: "QB", note: "Purdy's processing speed and accuracy within Shanahan's system make him one of the most efficient quarterbacks in football. His ability to identify and attack soft spots in coverage quickly is a genuine skill." },
    keyPlayer2: { name: "Christian McCaffrey", pos: "RB", note: "McCaffrey's versatility as both a runner and receiver out of the backfield creates matchup nightmares for linebackers and safeties. He is the offense's most important player and the focal point of every defensive game plan." },
    outlook: ["Kyle Shanahan's offensive system is the most creative in the league. His ability to use motion, shifts, and play-action to generate clean throws for Purdy makes the 49ers offense extraordinarily difficult to prepare for.", "San Francisco's defense is built around versatility and personnel flexibility. They can match any offensive formation and present multiple fronts.", "The 49ers are particularly dangerous in the first half. Shanahan front-loads game plans with schematic wrinkles designed to establish advantages before halftime adjustments."],
  },
  DET: {
    coach: "Dan Campbell", qb: "Jared Goff",
    offenseStyle: "physical, run-first attack that creates explosive passing opportunities off play-action",
    defenseStyle: "aggressive, assignment-sound defense that prioritizes stopping the run",
    strength: "offensive line that physically dominates at the point of attack",
    weakness: "pass coverage in the secondary when facing elite wide receiver groups",
    keyPlayer1: { name: "Jared Goff", pos: "QB", note: "Goff has evolved into one of the NFL's most accurate quarterbacks within Campbell's system. His ability to process quickly and deliver in rhythm makes the Lions' play-action passing game consistently explosive." },
    keyPlayer2: { name: "Amon-Ra St. Brown", pos: "WR", note: "St. Brown's ability to consistently create separation in the slot and convert on third downs has made him Goff's most reliable option. He leads the team in contested catch situations." },
    outlook: ["Dan Campbell has built a culture of toughness in Detroit that shows up in the fourth quarter. The Lions consistently outperform their opponents in the final fifteen minutes.", "Detroit's offensive line is the team's most significant competitive advantage. Their physical domination at the point of attack wears opposing defenses down over sixty minutes.", "Ford Field is one of the loudest environments in the NFC. The Lions' home-field advantage is genuine."],
  },
  GB: {
    coach: "Matt LaFleur", qb: "Jordan Love",
    offenseStyle: "West Coast passing attack with deep play-action shots and creative route combinations",
    defenseStyle: "zone-based coverage scheme that limits explosive plays and forces field goals",
    strength: "Jordan Love's deep ball accuracy and ability to attack all three levels of the field",
    weakness: "red zone efficiency when facing physical man coverage",
    keyPlayer1: { name: "Jordan Love", pos: "QB", note: "Love has emerged as one of the NFC's most dangerous quarterbacks. His arm talent in the deep game is exceptional, and his comfort in LaFleur's system has grown dramatically." },
    keyPlayer2: { name: "Jayden Reed", pos: "WR", note: "Reed's explosiveness in the slot and ability to create yards after the catch make him Love's most dangerous short-to-intermediate option." },
    outlook: ["Matt LaFleur's offensive system creates layered route combinations that attack every level of the defense. The Packers' ability to generate explosive plays down the field is their biggest offensive weapon.", "Green Bay's defense is built around limiting big plays and keeping opponents in manageable situations.", "Lambeau Field is one of the most iconic home-field advantages in professional sports."],
  },
  DAL: {
    coach: "Mike McCarthy", qb: "Dak Prescott",
    offenseStyle: "balanced, spread-formation attack that leverages Prescott's arm and CeeDee Lamb's talent",
    defenseStyle: "aggressive, Micah Parsons-anchored defense that creates havoc in opposing backfields",
    strength: "CeeDee Lamb's ability to create mismatches against any cornerback in the league",
    weakness: "road performance in elimination games has been a persistent concern",
    keyPlayer1: { name: "Dak Prescott", pos: "QB", note: "Prescott's arm talent and ability to operate in a spread formation make him one of the NFC's most productive passers. He's at his best when the Cowboys can establish early success and build rhythm." },
    keyPlayer2: { name: "CeeDee Lamb", pos: "WR", note: "Lamb is one of the best receivers in football. His combination of route running, yards after catch, and contested-catch ability makes him nearly impossible to match up against with a single cornerback." },
    outlook: ["AT&T Stadium gives Dallas a genuine home-field advantage. The Cowboys' record at home in prime-time games is excellent.", "Mike McCarthy's offense generates its best football when Prescott is in rhythm early.", "Micah Parsons' impact on the defensive side multiplies the effectiveness of the entire Cowboys defense."],
  },
  CIN: {
    coach: "Zac Taylor", qb: "Joe Burrow",
    offenseStyle: "vertical, precision passing attack built around Burrow's footwork and Ja'Marr Chase's explosiveness",
    defenseStyle: "multiple-coverage scheme that protects against the deep ball and limits explosive plays",
    strength: "Burrow-to-Chase connection that creates explosive plays against any coverage",
    weakness: "offensive line protection consistency has been an ongoing concern",
    keyPlayer1: { name: "Joe Burrow", pos: "QB", note: "Burrow is the most technically refined quarterback in the AFC. His footwork, pocket navigation, and touch on downfield throws make him extraordinarily dangerous when given time to operate." },
    keyPlayer2: { name: "Ja'Marr Chase", pos: "WR", note: "Chase's combination of speed, route precision, and ball-tracking ability makes him the most dangerous receiver in the AFC. His connection with Burrow is one of the best in professional football." },
    outlook: ["Cincinnati's offense is capable of scoring in bunches when Burrow is in rhythm. The Bengals' vertical passing game puts points on the board quickly.", "Zac Taylor's defense has improved each year, focusing on protecting against the explosive play.", "Paycor Stadium brings genuine energy when the Bengals are competitive."],
  },
  MIA: {
    coach: "Mike McDaniel", qb: "Tua Tagovailoa",
    offenseStyle: "speed-based, precision passing attack that leverages the NFL's deepest wide receiver corps",
    defenseStyle: "aggressive, pressure-first defense that generates turnovers",
    strength: "speed at the skill positions that creates explosive plays against any coverage",
    weakness: "durability concerns at quarterback have derailed multiple seasons",
    keyPlayer1: { name: "Tua Tagovailoa", pos: "QB", note: "When healthy, Tua is one of the AFC's most accurate passers. His ability to deliver on time and in rhythm makes Miami's speed-based offense extraordinarily difficult to defend." },
    keyPlayer2: { name: "Tyreek Hill", pos: "WR", note: "Hill remains the fastest receiver in professional football. His ability to threaten the defense vertically on every snap forces safeties to play deep, opening space for other receivers." },
    outlook: ["Miami's offense is built around getting the ball to playmakers in space. McDaniel's scheme leverages the Dolphins' speed advantage on every down.", "The Dolphins' defense is built to generate turnovers through aggressive coverage and pressure packages.", "Hard Rock Stadium presents challenges for visiting teams, particularly in the heat and humidity of early-season games."],
  },
  NYJ: {
    coach: "Robert Saleh", qb: "Aaron Rodgers",
    offenseStyle: "experience-driven, play-action attack built around Rodgers' football IQ and downfield precision",
    defenseStyle: "physical, man-coverage defense anchored by elite cornerback play",
    strength: "Rodgers' ability to dissect coverage and avoid sacks through quick processing",
    weakness: "offensive line protection in obvious passing situations",
    keyPlayer1: { name: "Aaron Rodgers", pos: "QB", note: "Rodgers' football IQ remains elite. His ability to process pre-snap information and manipulate defenses with eyes and pump fakes is unmatched." },
    keyPlayer2: { name: "Garrett Wilson", pos: "WR", note: "Wilson is one of the most technically refined route runners in the NFL. His ability to create separation against press coverage and make contested catches has made him the Jets' most dangerous offensive weapon." },
    outlook: ["New York's offense under Rodgers is built on precision and patience. The Jets protect the football and wait for the defense to give up an exploitable look.", "Robert Saleh's defense is built on physicality at the line of scrimmage.", "MetLife Stadium is a neutral-site-style environment that benefits the team that executes best."],
  },
  NE: {
    coach: "Jerod Mayo", qb: "Drake Maye",
    offenseStyle: "developing system built around Maye's arm talent and mobility",
    defenseStyle: "disciplined, scheme-first defense built on Belichick-era principles",
    strength: "defensive discipline and the developmental ceiling Drake Maye represents",
    weakness: "offensive line consistency and skill position depth around the young quarterback",
    keyPlayer1: { name: "Drake Maye", pos: "QB", note: "Maye is one of the most intriguing young quarterbacks in the league. His arm talent, processing speed, and mobility give New England a genuine foundational piece." },
    keyPlayer2: { name: "Ja'Lynn Polk", pos: "WR", note: "Polk's route running and ability to create separation in the slot give Maye a reliable intermediate target." },
    outlook: ["New England's offense is in development mode, but Maye's ceiling is genuinely elite.", "The Patriots' defensive culture remains a strength even in a transitional period.", "Gillette Stadium's crowd and weather conditions make it a challenging road environment."],
  },
  PIT: {
    coach: "Mike Tomlin", qb: "Russell Wilson",
    offenseStyle: "balanced, run-complemented passing attack that relies on Wilson's experience and mobility",
    defenseStyle: "multiple-front, pressure-generating defense with decades of scheme continuity",
    strength: "Mike Tomlin's ability to keep teams competitive regardless of roster construction",
    weakness: "offensive consistency and protecting Wilson in the pocket",
    keyPlayer1: { name: "Russell Wilson", pos: "QB", note: "Wilson's experience and football IQ give Pittsburgh a steady hand at quarterback. His ability to extend plays and make something out of broken situations remains valuable." },
    keyPlayer2: { name: "TJ Watt", pos: "OLB", note: "Watt is the most disruptive pass rusher in the AFC North. His ability to generate pressure on every down forces offensive lines to account for him with extra blockers." },
    outlook: ["Pittsburgh's defense is the team's identity. Mike Tomlin's defensive continuity gives the Steelers a genuine competitive advantage.", "Acrisure Stadium is one of the most intimidating environments for road teams in the AFC.", "Tomlin's teams never have losing records. Their discipline and situational football is an organizational strength."],
  },
  CLE: {
    coach: "Kevin Stefanski", qb: "Deshaun Watson",
    offenseStyle: "run-first, physical attack designed to control possession and limit risk",
    defenseStyle: "aggressive, Myles Garrett-anchored defense that disrupts in the backfield",
    strength: "Myles Garrett's impact at defensive end that makes the entire defense better",
    weakness: "offensive consistency and quarterback reliability with Watson's health history",
    keyPlayer1: { name: "Myles Garrett", pos: "DE", note: "Garrett is one of the best defensive players in professional football. His ability to generate pressure on every snap forces offensive coordinators to dedicate extra blockers." },
    keyPlayer2: { name: "Amari Cooper", pos: "WR", note: "Cooper's route precision and ability to win against press coverage give Cleveland a reliable downfield option that can move the chains on third down." },
    outlook: ["Cleveland's offense is built around controlling the line of scrimmage and running the football effectively.", "Myles Garrett's impact transforms Cleveland's defense into a legitimate threat against any offense.", "FirstEnergy Stadium brings genuine energy in AFC North divisional matchups."],
  },
  IND: {
    coach: "Shane Steichen", qb: "Anthony Richardson",
    offenseStyle: "dynamic, dual-threat system built around Richardson's exceptional physical tools",
    defenseStyle: "assignment-sound, zone-heavy scheme designed to limit explosive plays",
    strength: "Richardson's ceiling as a rushing threat that no linebacker can reliably stop",
    weakness: "Richardson's developmental consistency and decision-making in clutch moments",
    keyPlayer1: { name: "Anthony Richardson", pos: "QB", note: "Richardson's physical tools are extraordinary — his combination of arm strength and speed makes him a genuine dual-threat weapon." },
    keyPlayer2: { name: "Jonathan Taylor", pos: "RB", note: "Taylor remains one of the best pure runners in the AFC. His ability to create yards after contact and break tackles in the open field gives Indianapolis an explosive element." },
    outlook: ["Indianapolis's offensive ceiling is directly tied to Richardson's consistency.", "Shane Steichen's scheme is built to protect Richardson and create favorable situations.", "Lucas Oil Stadium creates a genuine home environment for Indianapolis."],
  },
  HOU: {
    coach: "DeMeco Ryans", qb: "C.J. Stroud",
    offenseStyle: "precise, quick-rhythm passing attack built around Stroud's processing and Nico Collins' explosiveness",
    defenseStyle: "aggressive, multiple-pressure scheme that creates chaos in opposing backfields",
    strength: "Stroud's ability to read coverages quickly and distribute to open receivers",
    weakness: "red zone execution against physical man-coverage defenses",
    keyPlayer1: { name: "C.J. Stroud", pos: "QB", note: "Stroud's football IQ is exceptional. His ability to process pre-snap information and deliver on time makes Houston's offense efficient on every down." },
    keyPlayer2: { name: "Nico Collins", pos: "WR", note: "Collins' combination of size and speed makes him Stroud's most dangerous downfield target. His ability to beat single coverage vertically gives Houston an explosive element." },
    outlook: ["Houston's offense is built on efficiency and quick processing. Ryans and Stroud have developed a sophisticated system that leverages the young quarterback's strengths.", "The Texans' defense is one of the most aggressive in the AFC. DeMeco Ryans' pressure packages create confusion in protection assignments.", "NRG Stadium creates a genuine home environment in Houston."],
  },
  TEN: {
    coach: "Brian Callahan", qb: "Will Levis",
    offenseStyle: "developing system built around Levis's arm strength and physical mobility",
    defenseStyle: "disciplined, zone-coverage scheme that limits explosive plays",
    strength: "young talent on both sides of the ball that creates long-term optimism",
    weakness: "offensive consistency and execution in situational football",
    keyPlayer1: { name: "Will Levis", pos: "QB", note: "Levis's arm strength and willingness to attack downfield give Tennessee an explosive element in the passing game." },
    keyPlayer2: { name: "Tony Pollard", pos: "RB", note: "Pollard's combination of speed and receiving ability out of the backfield makes him a genuine offensive weapon." },
    outlook: ["Tennessee's offense is in development mode, but their young talent shows flashes of significant upside.", "Brian Callahan's defense is focused on limiting the damage in a rebuild phase.", "Nissan Stadium brings genuine energy for big home games."],
  },
  JAX: {
    coach: "Doug Pederson", qb: "Trevor Lawrence",
    offenseStyle: "creative, spread-formation attack built around Lawrence's arm talent and receiver depth",
    defenseStyle: "multiple-coverage scheme that leverages their cornerback depth",
    strength: "Lawrence's playmaking ability that keeps Jacksonville competitive in any game",
    weakness: "consistency through the regular season and avoiding self-inflicted turnovers",
    keyPlayer1: { name: "Trevor Lawrence", pos: "QB", note: "Lawrence's arm talent and competitive drive make him one of the AFC's most dangerous quarterbacks when the Jaguars are executing." },
    keyPlayer2: { name: "Calvin Ridley", pos: "WR", note: "Ridley's route running precision and ability to create separation against press coverage give Lawrence a reliable deep option." },
    outlook: ["Jacksonville's offense is built on Lawrence's ability to make plays in structure and outside of it.", "Doug Pederson's scheme leverages Jacksonville's athlete depth and creates favorable matchups.", "TIAA Bank Field brings competitive energy when Jacksonville is winning."],
  },
  LAC: {
    coach: "Jim Harbaugh", qb: "Justin Herbert",
    offenseStyle: "balanced, physical attack that pairs Herbert's arm talent with a disciplined run game",
    defenseStyle: "aggressive, multiple-front defense that generates pressure with four rushers",
    strength: "Herbert's arm talent and the organizational discipline Harbaugh has installed",
    weakness: "offensive line consistency protecting Herbert in obvious passing situations",
    keyPlayer1: { name: "Justin Herbert", pos: "QB", note: "Herbert's combination of size, arm strength, and football IQ makes him one of the AFC's most talented quarterbacks. Under Harbaugh's disciplined system, he's become more decisive." },
    keyPlayer2: { name: "Keenan Allen", pos: "WR", note: "Allen's route precision and ability to win against zone coverage make him Herbert's most reliable option on third down." },
    outlook: ["Los Angeles's offense under Harbaugh is more disciplined and balanced. When Herbert can operate play-action off a functional run game, the offense reaches its ceiling.", "Jim Harbaugh's defensive philosophy prioritizes generating pressure with the front four.", "SoFi Stadium is a premium environment that creates challenges for both teams."],
  },
  LV: {
    coach: "Antonio Pierce", qb: "Gardner Minshew",
    offenseStyle: "efficient, game-management system built around protecting the football",
    defenseStyle: "aggressive, pressure-based defense designed to create short fields for the offense",
    strength: "Allegiant Stadium's atmosphere and a passionate fanbase",
    weakness: "quarterback limitations that cap the offense's ceiling in high-scoring games",
    keyPlayer1: { name: "Gardner Minshew", pos: "QB", note: "Minshew's football IQ and ability to protect the ball give Las Vegas a functional offensive floor. He's at his best when the Raiders can establish the run." },
    keyPlayer2: { name: "Davante Adams", pos: "WR", note: "Adams' route running precision is elite. His ability to create separation against any coverage makes him the Raiders' most reliable offensive weapon." },
    outlook: ["Las Vegas's offense is built on ball security and establishing the run.", "Antonio Pierce's defense is built on aggression and creating chaos in opposing backfields.", "Allegiant Stadium is one of the most visually spectacular environments in professional sports."],
  },
  DEN: {
    coach: "Sean Payton", qb: "Bo Nix",
    offenseStyle: "creative, play-action system designed to leverage Nix's mobility and Payton's scheme ingenuity",
    defenseStyle: "physical, multiple-front defense that disrupts opposing offenses at the line",
    strength: "Sean Payton's offensive creativity and the Mile High altitude advantage",
    weakness: "Nix's consistency and execution in clutch, high-leverage moments",
    keyPlayer1: { name: "Bo Nix", pos: "QB", note: "Nix's mobility and arm strength give Denver an explosive offensive element when he's in rhythm. His development under Payton's system has been encouraging." },
    keyPlayer2: { name: "Courtland Sutton", pos: "WR", note: "Sutton's combination of size and contested-catch ability makes him Nix's most reliable downfield target." },
    outlook: ["Denver's offense under Sean Payton is built on creativity and misdirection.", "Mile High Stadium's altitude creates a genuine performance advantage for Denver.", "Empower Field at Mile High brings electric energy when the Broncos are competitive."],
  },
  SEA: {
    coach: "Mike Macdonald", qb: "Geno Smith",
    offenseStyle: "balanced, quick-rhythm attack that leverages Smith's accuracy and a deep receiving corps",
    defenseStyle: "aggressive, Legion-of-Boom-inspired press-coverage scheme",
    strength: "CenturyLink Field's crowd noise and the 12th Man home-field advantage",
    weakness: "late-season consistency and ability to sustain drives against physical defenses",
    keyPlayer1: { name: "Geno Smith", pos: "QB", note: "Smith's accuracy and football IQ have made him a reliable starter. His ability to operate efficiently in the short-to-intermediate area gives Seattle a consistent offensive floor." },
    keyPlayer2: { name: "DK Metcalf", pos: "WR", note: "Metcalf's combination of size and speed makes him one of the NFC's most physically imposing wide receivers. His deep-ball threat forces safeties to play back." },
    outlook: ["Seattle's offense is built on efficiency and taking care of the football.", "Mike Macdonald's defensive system is built on press coverage and creating disruption at the line of scrimmage.", "Lumen Field is one of the loudest environments in professional football."],
  },
  LAR: {
    coach: "Sean McVay", qb: "Matthew Stafford",
    offenseStyle: "innovative, motion-heavy passing attack with creative pre-snap movement",
    defenseStyle: "aggressive, disruptive front that creates havoc at every level",
    strength: "McVay's scheme creativity and Stafford's experience in pressure situations",
    weakness: "offensive line depth and protecting Stafford against elite pass rushers",
    keyPlayer1: { name: "Matthew Stafford", pos: "QB", note: "Stafford's experience and competitiveness make him valuable in high-stakes situations. His willingness to attack downfield gives the Rams an explosive element McVay leverages effectively." },
    keyPlayer2: { name: "Cooper Kupp", pos: "WR", note: "Kupp's route precision and ability to find open space in zone coverage make him Stafford's most reliable option on critical downs." },
    outlook: ["Sean McVay's offensive system is the most innovative in the NFC.", "Los Angeles's defense has improved through strategic roster construction.", "SoFi Stadium is a premium environment that challenges visiting teams."],
  },
  ARI: {
    coach: "Jonathan Gannon", qb: "Kyler Murray",
    offenseStyle: "fast-paced, spread-option attack built around Murray's dual-threat ability",
    defenseStyle: "zone-heavy coverage scheme designed to limit explosive plays",
    strength: "Murray's elite mobility and the offense's ability to generate big plays quickly",
    weakness: "consistency and protecting Murray in the pocket against physical pass rushers",
    keyPlayer1: { name: "Kyler Murray", pos: "QB", note: "Murray's speed and agility make him one of the most dangerous quarterbacks in space. When healthy, his ability to extend plays and create out of structure gives Arizona an explosive element." },
    keyPlayer2: { name: "Marvin Harrison Jr.", pos: "WR", note: "Harrison Jr. brings elite physical tools to Arizona's passing game. His combination of size, speed, and polished route running makes him a legitimate star." },
    outlook: ["Arizona's offense under Gannon is building an identity around Murray's mobility and the young talent surrounding him.", "The Cardinals' defense prioritizes limiting big plays during a period of roster development.", "State Farm Stadium creates a decent home atmosphere for Arizona."],
  },
  ATL: {
    coach: "Raheem Morris", qb: "Kirk Cousins",
    offenseStyle: "dynamic, multi-weapon attack that leverages Cousins' accuracy and Bijan Robinson's versatility",
    defenseStyle: "aggressive, zone-based scheme designed to create takeaways",
    strength: "Bijan Robinson's dual-threat ability as both a runner and receiver out of the backfield",
    weakness: "Cousins' durability and ability to maintain efficiency under sustained defensive pressure",
    keyPlayer1: { name: "Kirk Cousins", pos: "QB", note: "Cousins brings accuracy and experience to Atlanta's offense. His ability to deliver in rhythm and exploit soft zones makes him reliable in game-management situations." },
    keyPlayer2: { name: "Bijan Robinson", pos: "RB", note: "Robinson's combination of power, speed, and receiving ability out of the backfield makes him one of the most complete running backs in the NFC." },
    outlook: ["Atlanta's offense is built around Robinson's versatility and Cousins' accuracy.", "Raheem Morris has built an aggressive defensive identity in Atlanta.", "Mercedes-Benz Stadium is one of the most modern facilities in professional sports."],
  },
  NO: {
    coach: "Dennis Allen", qb: "Derek Carr",
    offenseStyle: "balanced, precise attack built around the Saints' historical ability to manufacture points",
    defenseStyle: "physical, New Orleans-style defense built on shutting down the run",
    strength: "the Superdome atmosphere and decades of competitive culture",
    weakness: "Carr's consistency and offensive line protection in adverse situations",
    keyPlayer1: { name: "Derek Carr", pos: "QB", note: "Carr's experience and accuracy make him a reliable game manager in New Orleans' system. His ability to get the ball to his playmakers quickly is the foundation of the Saints' offensive identity." },
    keyPlayer2: { name: "Chris Olave", pos: "WR", note: "Olave's speed and route precision make him Carr's most dangerous downfield option. His vertical threat forces safeties to play deep." },
    outlook: ["New Orleans' offense generates competitive scores through precision and ball security.", "The Superdome crowd is one of the most impactful in the NFC South.", "Dennis Allen's defense prioritizes stopping the run and limiting possession time."],
  },
  TB: {
    coach: "Todd Bowles", qb: "Baker Mayfield",
    offenseStyle: "balanced, veteran-led attack that prioritizes ball security and big-play potential",
    defenseStyle: "aggressive, pressure-generating defense that leverages elite edge rusher talent",
    strength: "Mayfield's confidence and ability to deliver in critical game situations",
    weakness: "offensive consistency when the run game struggles to establish momentum",
    keyPlayer1: { name: "Baker Mayfield", pos: "QB", note: "Mayfield's confidence and arm talent have made him a genuine competitor in the NFC South. His ability to deliver in clutch situations gives Tampa Bay an explosive passing game." },
    keyPlayer2: { name: "Mike Evans", pos: "WR", note: "Evans' combination of size and competitiveness makes him one of the most reliable receivers in the NFC. His ability to win in contested situations has been consistent throughout his career." },
    outlook: ["Tampa Bay's offense under Bowles is built on balance and protecting Mayfield.", "Todd Bowles' defense is built on generating pressure and creating negative plays.", "Raymond James Stadium brings solid energy when Tampa Bay is competitive."],
  },
  CAR: {
    coach: "Dave Canales", qb: "Bryce Young",
    offenseStyle: "developing, creative system built around Young's processing ability and mobility",
    defenseStyle: "zone-based coverage scheme focused on limiting explosive plays during a rebuild",
    strength: "coaching development and Bryce Young's growing comfort in the system",
    weakness: "roster depth and the cumulative challenges of a rebuild on both sides of the ball",
    keyPlayer1: { name: "Bryce Young", pos: "QB", note: "Young's football intelligence and processing speed are genuine. His ability to navigate the pocket and make accurate throws in tight windows gives Carolina a foundational piece." },
    keyPlayer2: { name: "Adam Thielen", pos: "WR", note: "Thielen's experience and route running IQ give Young a reliable option in the intermediate area. His ability to find soft spots in zone coverage is the offensive unit's most consistent element." },
    outlook: ["Carolina's offense is in a developmental phase, but Young's growth within Canales' system has been encouraging.", "Dave Canales' defense is focused on limiting damage in a rebuild phase.", "Bank of America Stadium creates a solid home atmosphere for Carolina in competitive games."],
  },
  MIN: {
    coach: "Kevin O'Connell", qb: "Sam Darnold",
    offenseStyle: "creative, motion-heavy attack built around Justin Jefferson's talent",
    defenseStyle: "zone-heavy coverage scheme leveraging cornerback talent",
    strength: "Justin Jefferson's ability to create mismatches that cannot be eliminated by any coverage",
    weakness: "Darnold's consistency in critical moments and decision-making under pressure",
    keyPlayer1: { name: "Justin Jefferson", pos: "WR", note: "Jefferson is a generational talent who creates advantages against any coverage. His combination of route precision, contested-catch ability, and explosiveness after the catch makes him the most dangerous receiver in the NFC North." },
    keyPlayer2: { name: "Sam Darnold", pos: "QB", note: "Darnold's experience and mobility give Minnesota a functional quarterback in O'Connell's system. When he's decisive and gets the ball to Jefferson early, the Vikings' offense generates consistent production." },
    outlook: ["Kevin O'Connell's scheme is designed to maximize Jefferson's impact on every possession.", "Minnesota's defense is built around limiting the big play and creating pressure through stunts.", "US Bank Stadium is one of the loudest indoor environments in professional sports."],
  },
  CHI: {
    coach: "Ben Johnson", qb: "Caleb Williams",
    offenseStyle: "innovative, Williams-tailored system built around his arm talent and mobility",
    defenseStyle: "developing defensive scheme focused on creating turnovers",
    strength: "Williams' ceiling as a passer and the offensive creativity Ben Johnson brings",
    weakness: "youth and inexperience in high-leverage situations throughout the roster",
    keyPlayer1: { name: "Caleb Williams", pos: "QB", note: "Williams' arm talent and mobility make him one of the most exciting quarterbacks in the NFL. His ability to make difficult throws in tight windows and extend plays with his legs gives Chicago an explosive ceiling." },
    keyPlayer2: { name: "DJ Moore", pos: "WR", note: "Moore's route precision and ability to create separation against press coverage give Williams a reliable target at every level of the field." },
    outlook: ["Chicago's offense under Ben Johnson is building something genuinely exciting.", "The Bears' defense is in development mode but shows improvement.", "Soldier Field's historic atmosphere creates a meaningful home-field advantage."],
  },
  WAS: {
    coach: "Dan Quinn", qb: "Jayden Daniels",
    offenseStyle: "dynamic, RPO-heavy attack built around Daniels' elite dual-threat ability",
    defenseStyle: "aggressive, multiple-front defense that pressures quarterbacks at a high rate",
    strength: "Daniels' mobility and the offense's ability to create explosive plays through the air and on the ground",
    weakness: "experience managing high-pressure playoff-caliber environments",
    keyPlayer1: { name: "Jayden Daniels", pos: "QB", note: "Daniels is one of the most exciting young quarterbacks in the league. His elite mobility combined with genuine arm talent makes the Commanders' offense impossible to defend without accounting for his running threat." },
    keyPlayer2: { name: "Terry McLaurin", pos: "WR", note: "McLaurin's ability to create separation vertically and compete in contested situations makes him Daniels' most dangerous downfield target." },
    outlook: ["Washington's offense under Dan Quinn is one of the most dynamic in the NFC.", "Quinn's defense is built on pressure and taking away the opponent's primary option.", "Northwest Stadium brings competitive energy for Washington's home games."],
  },
  NYG: {
    coach: "Brian Daboll", qb: "Daniel Jones",
    offenseStyle: "run-first, physical attack designed to control the clock and protect the quarterback",
    defenseStyle: "multiple-front defense built around creating sacks and disrupting timing",
    strength: "Saquon Barkley's ability to create explosive plays as both a runner and receiver",
    weakness: "Jones' consistency in generating the downfield production needed to complement the run game",
    keyPlayer1: { name: "Daniel Jones", pos: "QB", note: "Jones' mobility and competitive drive give New York a quarterback capable of manufacturing plays outside of structure." },
    keyPlayer2: { name: "Darius Slayton", pos: "WR", note: "Slayton's speed and ability to create vertical opportunities make him the Giants' most dangerous downfield threat." },
    outlook: ["New York's offense is built on controlling the clock and establishing the run game.", "Brian Daboll's defense is built on disrupting opposing quarterbacks through pressure.", "MetLife Stadium creates a competitive environment for New York."],
  },
};

export function getNFLProfile(abbr: string): TeamProfile {
  return NFL_TEAM_PROFILES[abbr.toUpperCase()] ?? {
    coach: "Head Coach", qb: "the quarterback",
    offenseStyle: "balanced offensive attack", defenseStyle: "disciplined defensive scheme",
    strength: "depth and competitive culture", weakness: "consistency in high-leverage situations",
    keyPlayer1: { name: "Starting QB", pos: "QB", note: "Brings leadership and playmaking ability to the offense." },
    keyPlayer2: { name: "Lead Receiver", pos: "WR", note: "Provides the offense with a reliable downfield option." },
    outlook: ["This team will look to establish their identity early.", "Their defensive scheme is designed to limit the opponent's explosive plays.", "Late-game execution will be key to their success."],
  };
}
