/**
 * Generates one unique blog post per Seattle Seahawks player.
 * Run: npx tsx scripts/generate-seahawks-player-posts.ts
 * Existing posts are never overwritten.
 */

import "dotenv/config";
import mongoose from "mongoose";
import slugify from "slugify";

const MONGO_URI = process.env.MONGODB_URI || "";
if (!MONGO_URI) { console.error("MONGODB_URI not set"); process.exit(1); }

// ── Minimal models ────────────────────────────────────────────────────────────

const PostSchema = new mongoose.Schema({
  slug:            { type: String, required: true, unique: true },
  title:           { type: String, required: true },
  excerpt:         { type: String, required: true },
  content:         { type: String, required: true },
  coverImage:      { type: String },
  author:          { type: String, default: "NFL Predictions Hub Staff" },
  tags:            { type: [String], default: [] },
  published:       { type: Boolean, default: true },
  metaTitle:       { type: String },
  metaDescription: { type: String },
  schemaMarkup:    { type: String },
}, { timestamps: true });

const Post = mongoose.models?.Post || mongoose.model("Post", PostSchema);

// ── Seahawks roster ───────────────────────────────────────────────────────────

interface SeahawksPlayer {
  name: string;
  pos: string;
  number: number;
  age?: number;
  years?: number;
  overview: string;
  strengths: string[];
  weaknesses: string[];
  performance: string;
  impact: string;
  outlook: string;
}

const SEAHAWKS_ROSTER: SeahawksPlayer[] = [
  {
    name: "Sam Darnold",
    pos: "Quarterback",
    number: 14,
    age: 28,
    years: 7,
    overview: "Sam Darnold is the Seattle Seahawks' Super Bowl LX champion quarterback — the central figure in one of the great redemption narratives in professional football history. Written off by multiple franchises before landing in Seattle, Darnold delivered a championship performance in 2025 that silenced every doubt about his ability to play winning quarterback at the highest level. His accurate pocket passing and improved decision-making in Mike Macdonald's system proved that the right environment transforms a quarterback's career.",
    strengths: [
      "Super Bowl LX champion whose championship performance validated the organizational belief that the right system and coaching could unlock his potential — Darnold delivered when it mattered most.",
      "Accurate pocket passer whose improved decision-making in Macdonald's system has eliminated the turnover issues that defined his early career with the Jets.",
      "Arm talent that was always present — Darnold can make every throw required by an NFL offense, and his improved processing speed has finally allowed that talent to produce consistent results.",
      "Championship experience and the confidence of having won the Super Bowl give him a competitive foundation that younger quarterbacks cannot replicate.",
    ],
    weaknesses: [
      "Consistency across a full 17-game season at the level he achieved during the Super Bowl run is the primary question — peak performance versus sustained excellence.",
      "Turnover avoidance requires continued discipline — the decision-making improvements that powered the championship must be maintained against defenses game-planning specifically for him in 2026.",
      "Mobility has never been his strongest trait, requiring the offensive line to protect him consistently for the offense to function at its ceiling.",
    ],
    performance: "Darnold's Super Bowl LX performance was the culmination of a career rebuilt through professional adversity and finally rewarded by championship success. His 2025 season under Macdonald was the most efficient of his professional career, and the confidence generated by winning the Super Bowl creates a foundation for sustained excellence.",
    impact: "Darnold is the champion quarterback around whom everything in Seattle is built. His presence gives the Seahawks the credibility of defending champions and the confidence of a locker room that knows what it takes to win. His improved decision-making is the cornerstone of the offense Macdonald designs.",
    outlook: "Darnold enters 2026 as a defending Super Bowl champion with something new to prove — that his 2025 wasn't lightning in a bottle but the beginning of a sustained championship-caliber career. With JSN, Kupp, and the championship core around him, the Seahawks are legitimate Super Bowl contenders and Darnold is their proven leader.",
  },
  {
    name: "Jaxon Smith-Njigba",
    pos: "Wide Receiver",
    number: 11,
    age: 23,
    years: 3,
    overview: "Jaxon Smith-Njigba is the Seattle Seahawks' AP Offensive Player of the Year and the best receiver in the NFC. His 2025 season — 1,793 receiving yards that broke franchise records and earned him the league's top offensive honor — established him as a generational receiving talent who has arrived at his absolute prime at just 23 years old. In three professional seasons, JSN has gone from promising prospect to the most decorated offensive player in the NFL.",
    strengths: [
      "AP Offensive Player of the Year 2025 with 1,793 receiving yards — statistically one of the greatest individual receiver seasons in NFL history, and earned at age 22.",
      "Complete receiver whose route running, hands, YAC production, and contested-catch ability operate at elite levels simultaneously — JSN has no significant receiving weakness.",
      "Separation creation that is genuinely elite against any coverage — man, zone, bracket, or press, JSN consistently finds open space and exploits it.",
      "Age 23 entering his prime means the best of his career may still be ahead — the most dangerous trajectory in professional football belongs to a player who won Offensive Player of the Year at 22.",
    ],
    weaknesses: [
      "As the clear number-one option, defenses will commit their best corner and additional safety help to eliminating him — sustained production against intensified coverage is the 2026 challenge.",
      "Size at 6'0\" means some jump-ball situations in the red zone favor physically larger corners, though his catching ability compensates significantly.",
    ],
    performance: "JSN's 2025 season was one of the most dominant individual receiver campaigns in recent NFL history. His ability to produce 1,793 yards while playing on a team that reached the Super Bowl — drawing every defensive team's best coverage attention — confirms that his talent operates at a level above ordinary elite production.",
    impact: "JSN is the most important offensive player on a Super Bowl champion roster. His presence demands coverage resources that benefit every other player in Seattle's offense — Cooper Kupp, Darnold's checkdowns, and the run game all improve because JSN draws the coverage attention he receives.",
    outlook: "JSN enters 2026 as the best receiver in the NFC and a legitimate candidate for the first back-to-back Offensive Player of the Year award. His age, talent, and championship experience create a ceiling that may be the highest of any offensive player in professional football. The 2026 Seahawks offense is built around his continued dominance.",
  },
  {
    name: "Cooper Kupp",
    pos: "Wide Receiver",
    number: 10,
    age: 31,
    years: 9,
    overview: "Cooper Kupp is the Seattle Seahawks' veteran wide receiver legend — the 2021 Triple Crown winner who joined from the Los Angeles Rams to contribute 593 receiving yards during Seattle's Super Bowl LX run. A route running genius whose technical precision and system mastery make him valuable far beyond his athletic profile, Kupp brings veteran wisdom, championship experience, and the ability to exploit coverage vacated by JSN to a receiving corps that is already the most dangerous in the NFC.",
    strengths: [
      "Route running precision that is among the best in professional football history — Kupp's ability to manipulate coverage with tempo changes, head fakes, and double moves generates separation that athletically superior receivers cannot match.",
      "Championship pedigree combining his Super Bowl LVI ring from the Rams with his contribution to Seattle's Super Bowl LX victory — Kupp has competed and succeeded at the absolute highest level.",
      "System mastery and football intelligence that allow him to find open windows in complex defensive schemes faster than any other receiver on the roster.",
      "Veteran leadership and mentorship that accelerate JSN's development as a complete receiver.",
    ],
    weaknesses: [
      "Age at 31 has reduced his explosiveness and long speed — Kupp is dependent on precision and scheme rather than athleticism to separate.",
      "Injury history over the last several seasons has limited his availability, creating roster management concerns.",
      "As the second receiver behind JSN, his target volume and production totals reflect a complementary role.",
    ],
    performance: "Kupp's 593-yard contribution during Seattle's Super Bowl run demonstrated that even in a complementary role, his route running precision and system understanding produce meaningful production. His ability to function as a high-quality number-two receiver on a championship team is exactly what Seattle needs.",
    impact: "Kupp's impact on Seattle's offense extends beyond his individual statistics. The coverage resources that JSN demands create the exact single-coverage situations that Kupp's route running exploits most efficiently. His veteran presence and mentorship of JSN are cultural contributions that elevate the organization.",
    outlook: "Kupp enters 2026 as the veteran complement whose most important contributions may be in the meeting room as much as on the field. A healthy Kupp in a complementary role to JSN gives Seattle the best receiver pairing in the NFC — one that combines generational youth with the wisdom of a Triple Crown winner.",
  },
  {
    name: "Zach Charbonnet",
    pos: "Running Back",
    number: 26,
    age: 24,
    years: 3,
    overview: "Zach Charbonnet is the Seattle Seahawks' featured running back and the physical ground game anchor of a championship offense. Stepping into the starter role after Kenneth Walker III's departure, Charbonnet brings power, durability, and the between-the-tackles toughness that has always been central to Seattle's offensive identity under every coaching regime.",
    strengths: [
      "Physical power running that generates yards between the tackles and after contact — Charbonnet's combination of size and contact balance makes him difficult to bring down with initial tackles.",
      "Workhorse mentality and the durability to handle a true featured-back workload across a full 17-game season.",
      "Youth at 24 with the developmental upside to continue improving as a receiver and pass protector.",
    ],
    weaknesses: [
      "Top-end open-field speed is adequate but not elite — Charbonnet relies on power and vision rather than outrunning defenders.",
      "Receiving production out of the backfield is still developing as a featured element of his game.",
    ],
    performance: "Charbonnet has been a productive starter who brings physical credibility to Seattle's ground game. His power running style grounds an offense that otherwise leans on JSN's explosiveness and Darnold's passing, providing the physical balance that championship offenses require.",
    impact: "Charbonnet's ground game production makes Seattle's play-action passing — which Darnold has executed effectively — more dangerous by forcing defensive commitment to the run. His physical presence is the foundation that opens the passing concepts that generate explosive plays.",
    outlook: "Charbonnet enters 2026 as the featured back on a Super Bowl champion roster. His continued development as a three-down back could elevate him into the conversation as one of the better young running backs in the NFC West.",
  },
  {
    name: "AJ Barner",
    pos: "Tight End",
    number: 48,
    age: 23,
    years: 2,
    overview: "AJ Barner is the Seattle Seahawks' athletic developing tight end who has been carving out an increasing role in Mike Macdonald's offense. A fluid athlete with receiving upside that has generated organizational excitement, Barner represents Seattle's investment in a long-term tight end solution that can contribute meaningfully alongside JSN and Kupp.",
    strengths: [
      "Athletic movement skills for the tight end position that allow him to align in multiple formations and create separation against linebackers in the seam.",
      "Developing receiving ability that has shown improvement each professional season.",
      "Youth and upside at 23 — Barner is ascending toward his ceiling with continued NFL experience.",
    ],
    weaknesses: [
      "Blocking consistency as an in-line tight end needs continued development.",
      "Limited professional experience means route precision and coverage recognition are still maturing.",
    ],
    performance: "Barner has been a developing contributor whose growing role reflects the coaching staff's confidence in his trajectory. His athletic tools give Seattle a tight end option that creates genuine mismatch potential.",
    impact: "Barner's growing role adds a seam-running dimension to Seattle's offense that forces defenses to account for a fourth receiving option beyond JSN, Kupp, and the running back screen game.",
    outlook: "Barner enters 2026 with genuine upside to become a featured receiving tight end within the next two seasons. His development in Macdonald's system and the reps gained during the championship run give him a strong foundation for expanded production.",
  },
  {
    name: "Rashid Shaheed",
    pos: "Wide Receiver",
    number: 19,
    age: 26,
    years: 4,
    overview: "Rashid Shaheed is the Seattle Seahawks' deep speed threat and third receiver complement to JSN and Kupp. A player who has built a career on elite straight-line speed and the ability to threaten the vertical game, Shaheed gives Macdonald a third element of the passing game that forces defenses to account for the deep ball on every play.",
    strengths: [
      "Elite straight-line speed that immediately qualifies him as a legitimate deep threat — Shaheed forces safety rotation that benefits JSN and Kupp underneath.",
      "Explosive big-play ability when given separation on vertical routes — his speed creates the kind of game-changing moments that affect defensive positioning throughout a game.",
      "Complementary role that perfectly fits a championship roster — Shaheed does not need to be a featured option to have a significant impact.",
    ],
    weaknesses: [
      "Route running precision in the short and intermediate areas is below JSN and Kupp's elite level.",
      "Consistency against elite press corners who can disrupt his vertical releases is a weakness that limits his effectiveness in some game situations.",
    ],
    performance: "Shaheed has been an important depth piece on the Seahawks' championship roster, providing the deep threat dimension that prevents defenses from completely committing to stopping JSN and Kupp.",
    impact: "Shaheed's speed forces safeties to respect the deep ball, which creates the coverage spacings that JSN and Kupp exploit in the intermediate areas. His role as a deep threat is multiplicative — it makes every other receiver more dangerous even when he doesn't touch the ball.",
    outlook: "Shaheed enters 2026 as the third receiver on a championship roster — a role that requires specific execution rather than featured production. His contributions will be focused and meaningful even if the statistics don't reflect the full scope of his impact.",
  },
  {
    name: "Drew Lock",
    pos: "Quarterback",
    number: 2,
    age: 29,
    years: 7,
    overview: "Drew Lock is the Seattle Seahawks' veteran backup quarterback and a familiar presence in the Northwest. A former second-round pick who has navigated multiple NFL stops, Lock provides Darnold with reliable backup insurance and gives Macdonald confidence that the offense can survive short-term injury absences without dramatic performance decline.",
    strengths: [
      "Arm strength and deep-ball ability that can execute the vertical elements of Macdonald's offensive concepts.",
      "Familiarity with Seattle's system built through multiple seasons in the organization.",
      "Veteran experience across seven professional seasons that provides situational stability in backup roles.",
    ],
    weaknesses: [
      "Starting-caliber consistency has not been established despite multiple opportunities — Lock is best suited to the backup role.",
      "Decision-making under pressure has been inconsistent throughout his career.",
    ],
    performance: "Lock has been a capable backup who knows the system and can maintain offensive functionality if Darnold misses limited time. His deep ball gives the Seahawks an emergency option who can threaten defenses vertically.",
    impact: "Lock's presence allows Macdonald to gameplan without catastrophic risk — a capable backup who understands the offense means the Super Bowl defense can keep Seattle competitive even in Darnold's absence.",
    outlook: "Lock enters 2026 in a clearly defined backup role. His familiarity with the Seahawks' system and his loyalty to the organization make him a valuable roster member for the defending champions.",
  },
  {
    name: "Uchenna Nwosu",
    pos: "Linebacker",
    number: 42,
    age: 28,
    years: 7,
    overview: "Uchenna Nwosu is the Seattle Seahawks' edge rusher and a key piece of Mike Macdonald's Super Bowl-winning defensive system. A pass rusher whose athleticism and effort have been consistent contributors to Seattle's defensive success, Nwosu provides the edge pressure that forces quarterbacks into the coverage traps Macdonald designs.",
    strengths: [
      "Athletic edge rushing ability that generates consistent pressure from the perimeter — Nwosu's first-step quickness and pass-rush effort produce disruption.",
      "Seven seasons of professional experience provide the situational intelligence to execute Macdonald's complex defensive concepts.",
      "Effort and motor that generate value beyond recorded statistics through consistent pursuit and disruption.",
    ],
    weaknesses: [
      "Elite sack production has been inconsistent — Nwosu is a productive pass rusher who falls short of the top-tier edge rushers in terms of individual dominance.",
      "Run defense assignment execution against power running attacks needs continued development.",
    ],
    performance: "Nwosu has been a solid starter in Macdonald's defensive system, providing consistent edge pressure that contributed to Seattle's championship defensive performance. His production is reliable if not elite.",
    impact: "Nwosu's edge pressure forces quarterbacks to navigate the clock management that Macdonald's coverage schemes are designed to punish. His consistent contribution to the pass rush is an important piece of the defensive system that won a Super Bowl.",
    outlook: "Nwosu enters 2026 as a proven contributor on a defending champion. His continued production in Macdonald's system gives Seattle reliable edge pressure that complements the secondary's elite coverage ability.",
  },
  {
    name: "Devon Witherspoon",
    pos: "Cornerback",
    number: 21,
    age: 24,
    years: 3,
    overview: "Devon Witherspoon is the Seattle Seahawks' elite cornerback and one of the best press corners in professional football. A Pro Bowl-caliber defender whose aggressive coverage style and ball skills have been a cornerstone of Seattle's championship defense, Witherspoon brings the kind of coverage ability that allows Macdonald to design schemes that put every opposing receiver in an impossible situation.",
    strengths: [
      "Elite press coverage technique that disrupts receiver routes at the line of scrimmage — Witherspoon's hand fighting and jam ability are among the best in the AFC West.",
      "Ball skills and turnover production that make him a game-changer in coverage — Witherspoon's interceptions and pass breakups contribute directly to championship-caliber defensive performance.",
      "Physical and competitive style that fits perfectly with Macdonald's aggressive defensive identity.",
      "Youth at 24 in his third season means he is ascending rather than maintaining — the best of his career may still be ahead.",
    ],
    weaknesses: [
      "Aggressive press style occasionally creates vulnerability on double-move routes when he bites on initial releases.",
      "Experience against the most sophisticated route runners in the league is still accumulating.",
    ],
    performance: "Witherspoon has been one of the best cornerbacks in the NFC West, playing a central role in the defense that won Super Bowl LX. His coverage ability against opposing number-one receivers is genuinely elite, and his production in the championship run validated his draft pedigree.",
    impact: "Witherspoon's ability to lock down the opposing number-one receiver allows Macdonald to use safeties and help coverage elsewhere, creating defensive flexibility that makes the entire coverage scheme more effective. His individual coverage excellence is the cornerstone of Seattle's secondary.",
    outlook: "Witherspoon enters 2026 as a Pro Bowl cornerback and a player with legitimate All-Pro upside. Continued development at 24 on a championship roster gives him one of the highest defensive ceilings in the NFC West.",
  },
  {
    name: "Tariq Woolen",
    pos: "Cornerback",
    number: 27,
    age: 26,
    years: 4,
    overview: "Tariq Woolen is the Seattle Seahawks' elite length cornerback and the emerging star whose blanket coverage has been a critical element of Macdonald's championship defense. With elite length and closing speed that make him one of the most intimidating press corners in the NFC, Woolen has developed from raw athletic prospect into a legitimate All-Pro caliber starter.",
    strengths: [
      "Elite length at 6'4\" that creates coverage mismatches against receivers who have never faced a corner with his size — Woolen's wingspan and reach disrupt routes and passing lanes in ways that normal-sized corners cannot.",
      "Elite closing speed that eliminates the deep ball on any route he covers — Woolen can recover from any initial separation because of his track-star speed.",
      "Blanket coverage ability that has developed rapidly through four professional seasons, earning him consideration as one of the top corners in the NFC.",
    ],
    weaknesses: [
      "Coverage technique against experienced route runners who use leverage and precision to compensate for size disadvantages is still refining.",
      "Physicality in press situations against receivers who can match his strength is an occasional vulnerability.",
    ],
    performance: "Woolen's development into a top-10 cornerback in the NFC has been one of the most impressive trajectories of any defensive back in the conference. His size-speed combination is rare, and his technical refinement has converted raw athletic tools into legitimate All-Pro production.",
    impact: "Woolen alongside Witherspoon gives Seattle the best cornerback tandem in the NFC West and one of the best in the entire conference. The two together allow Macdonald to deploy the most aggressive and versatile defensive coverage schemes in professional football.",
    outlook: "Woolen enters 2026 as a legitimate All-Pro candidate whose continued development at 26 suggests his best football is still ahead. A dominant 2026 season alongside Witherspoon could cement Seattle's secondary as the best in the conference.",
  },
];

// ── Content generator ─────────────────────────────────────────────────────────

function generatePlayerPost(player: SeahawksPlayer) {
  const slug = slugify(`seattle-seahawks-${player.name}-player-profile-2026`, {
    lower: true, strict: true,
  });

  const title = `${player.name} — Seattle Seahawks ${player.pos} | 2026 Player Profile & Analysis`;
  const excerpt = `Complete 2026 player profile for Seattle Seahawks ${player.pos} ${player.name}. Strengths, weaknesses, performance analysis, and season outlook under head coach Mike Macdonald.`;

  const strengthsHtml = player.strengths
    .map((s) => `<li>${s}</li>`)
    .join("\n");

  const weaknessesHtml = player.weaknesses
    .map((w) => `<li>${w}</li>`)
    .join("\n");

  const content = `
<h2>Player Overview</h2>
<p>${player.overview}</p>

<h2>Strengths</h2>
<ul>
${strengthsHtml}
</ul>

<h2>Weaknesses</h2>
<ul>
${weaknessesHtml}
</ul>

<h2>Performance &amp; Role</h2>
<p>${player.performance}</p>

<h2>Impact on the Seahawks</h2>
<p>${player.impact}</p>

<h2>2026 Season Outlook</h2>
<p>${player.outlook}</p>

<p><em>Analysis based on the 2026 Seattle Seahawks roster and the system installed by head coach Mike Macdonald.</em></p>
`.trim();

  const tags = [
    "Seattle Seahawks",
    "Seahawks",
    "NFC West",
    "Super Bowl LX Champions",
    player.name,
    player.pos,
    "Seahawks Player Profile",
    "NFL Player Analysis",
    "2026 NFL Season",
    "Mike Macdonald",
  ];

  return {
    slug,
    title,
    excerpt,
    content,
    author: "NFL Predictions Hub Staff",
    tags,
    published: true,
    metaTitle: `${player.name} | Seattle Seahawks ${player.pos} Profile 2026 — NFL Predictions Hub`,
    metaDescription: excerpt,
  };
}

// ── Main ──────────────────────────────────────────────────────────────────────

async function main() {
  await mongoose.connect(MONGO_URI);
  console.log("Connected to MongoDB");

  let created = 0;
  let skipped = 0;

  for (const player of SEAHAWKS_ROSTER) {
    const doc = generatePlayerPost(player);
    const existing = await Post.exists({ slug: doc.slug });

    if (existing) {
      console.log(`  ⟳ skip  ${player.name}`);
      skipped++;
      continue;
    }

    await Post.create(doc);
    console.log(`  ✎ gen   ${player.name}`);
    created++;
  }

  console.log(`\nDone. ${created} created, ${skipped} skipped (already exist).`);
  await mongoose.disconnect();
}

main().catch((err) => { console.error(err); process.exit(1); });
